<div>

    <h4>A title maybe</h4>

    <p>the content</p>

    <div dir="ltr"><div>Su servidor,</div><div>Fjor</div><div>------------------------------<wbr>-----------------------<br>
        Ing. Francisco de Jesús Orozco Ruiz<br>
        Administración de Servicios de Red e Internet<br>Coordinación de Tecnologías de la Información (CTI/OTIC)<br>
        Centro de Enseñanza Técnica Industrial (CETI) - GDL/MX<br>
        (52-33) 3641-3250 Ext 238<br>
        </div><div><br></div><div>[2022 - Año de Ricardo Flores Magón, escritor, anarquista y filósofo, precursor de la Revolución Mexicana]</div><div><span style="font-size:x-small">De conformidad con el inciso a) del artículo 57 del “Acuerdo por el que se emiten las políticas y disposiciones para impulsar el uso y&nbsp;</span><span style="font-size:x-small">aprovechamiento de la Informática,&nbsp;</span><span style="font-size:x-small">el&nbsp;</span></div><div><span style="font-size:x-small">gobierno digital, las tecnologías de la información y comunicación, y la seguridad de la información&nbsp;</span><span style="font-size:x-small">en la Administración Pública Federal" publicado en el Diario&nbsp;</span><span style="font-size:x-small">Oficial&nbsp;</span></div><div><span style="font-size:x-small">de la Federación el 6 de septiembre de 2021, l</span><span style="font-size:x-small">a información&nbsp;</span><span style="font-size:x-small">contenida en correos institucionales es de carácter confidencial y su tratamiento es con estricta observancia&nbsp;</span></div><div><span style="font-size:x-small">de los&nbsp;</span><span style="font-size:x-small">principios&nbsp;</span><span style="font-size:x-small">de licitud, finalidad, lealtad, consentimiento,&nbsp;</span><span style="font-size:x-small">calidad, proporcionalidad, información y responsabilidad establecidos en&nbsp;</span><span style="font-size:x-small">la Ley General de&nbsp;</span><span style="font-size:x-small">Protección de Datos&nbsp;</span></div><div><span style="font-size:x-small">Personales en Posesión de Sujetos Obligados.&nbsp;</span><span style="font-size:x-small">La Coordinación de Tecnologías en Información y el área de Servicios de Red e Internet del Centro de Enseñanza Técnica&nbsp;</span></div><div><span style="font-size:x-small">Industrial, como Organismo Público&nbsp;</span><span style="font-size:x-small">Descentralizado del Gobierno Federal, son responsables de la posesión de datos personales referente a los titulares mencionados; por&nbsp;</span></div><div><span style="font-size:x-small">lo que, con&nbsp;</span><font size="1">fundamento en el artículo 3 fracción XXXII, XXXIII, 17, 18, 22 fracción II, 42, 66 fracción II y 67, le transfieren los datos personales anexos en este correo para&nbsp;</font></div><div><span style="font-size:x-small">que sean utilizados en el ejercicio de sus facultades conferidas, con observancia en lo dispuesto en la mencionada Ley General de Protección de Datos Personales en&nbsp;</span></div><div><span style="font-size:x-small">Posesión&nbsp;</span><span style="font-size:x-small">de Sujetos Obligados, sus Lineamientos para el sector Público y las demás disposiciones aplicables. Sin embargo, si no es Ud. el destinatario de este&nbsp;</span><span style="font-size:x-small">mensaje,&nbsp;</span></div><div><span style="font-size:x-small">no tiene autorización para hacer uso del contenido o transferirlo a terceros.</span></div></div>

</div>